### ISSUE TITLE
Needs option to return row when inserting

### ISSUE THREAD

**Issue by jacobg** [keithf4/pg_partman#103]
The following article does a good job of explaining a Hibernate error when inserting a record using a trigger on master table that returns NULL:
http://blog.akquinet.de/2015/08/04/postgresql-partitioned-tables-and-hibernate/

I have not tested pg_partman but from inspecting the code it looks like its insert trigger does return NULL. It would be great to have an option for Hibernate compatibility by using a strategy to return the inserted row, either using the INSERT+INSERT+DELETE approach described in the article, or by using a rule.

**Comment by keithf4** [comment]
Using rules for partitioning introduces race conditions that are very difficult to deal with. Using only triggers instead solves them for the most part, so I chose that method.
https://web.archive.org/web/20140218132103/http://www.fuzzy.cz/en/articles/automatic-management-of-partitions-in-postgresql

The method of doing INSERT+INSERT+DELETE turns 1 write operation into 3, making the performance for high-traffic tables tank pretty spectacularly. Having that option would also add a lot of complexity to pg_partman that I do not want to do at this time.

This is a problem with table inheritance in general with postgres, not just a partitioning issue. Until partitioning is built in, or inheritance gets some redesigns, there's really no perfect answer to this issue right now. There are several different method of partitioning that all try to solve this and ones that I've seen that actually allow a return number all have large performance penalties (as the linked article itself states), so I designed pg_partman to be the most performant since that's what our users needed. 

Your article also describes how to disable the row count check in Hibernate, so if you need to use pg_partman, I'd agree with the article and use that recommended method.

**Comment by jacobg** [comment]
Thanks Keith. I totally understand what you're saying. We're starting to do some performance evaluations of partitioned tables, and I wanted to evaluate the actual cost of the extra db operations to return the row. The downside of turning of Hibernate's row count check is that we have to annotate every Hibernate model with the sql insert query for that table, which is an annoying Hibernate quirk of having to just disable the row count check.
