### ISSUE TITLE
Zabbix does not make use of partition constraints

### ISSUE THREAD

**Issue by cyberjacob** [keithf4/pg_partman#109]
Zabbix does not make use of the partition constraints created by pg_partman.

This appears to be caused by the constraints being cast to a datatime (via `to_timestamp(clock::double precision)`) whereas Zabbix uses the date as raw seconds since the epoch.

Example query with this issue:
`select * from history_uint where clock < 1234567890;`

Query that does not experience this issue:
`select * from history_uint where to_timestamp(clock::double precision) < '2016-01-30 00:00:00+00';`

**Comment by keithf4** [comment]
Sorry for the delay on this. Was running into some issues with this new constraint that another issue helped solve (https://github.com/keithf4/pg_partman/issues/118). Version 2.4.0 should now create an additional integer constraint on child tables so that using integer values in queries will allow constraint exclusion to work. Note this will only add constraints to newly created child tables. You'll have to go back and add them on any existing child tables manually (or re-partition the set).
