### ISSUE TITLE
Creating partitions from data in parent table / skipping intermediate partitions with no data

### ISSUE THREAD

**Issue by kayvonr** [keithf4/pg_partman#110]
Hey there - this is a potential issue; wondering if this is expected and if so if there is a solution, if not if there is a workaround.

Say you have a table of reporting data (called e.g. reporting_data), partitioned by day with partitions and data for, say, January 1-5 with premake value of 1 (e.g. reporting_data_p2016_01_01, reporting_data_p2016_01_02, reporting_data_p2016_01_03, reporting_data_p2016_01_04, reporting_data_p2016_01_05, reporting_data_p2016_01_06). It then receives no further data for a few months, causing new partitions to stop being created during run_maintenance() runs (as there is no new data). This part is fine and expected. Now say the table then starts to receive new data after a while, e.g. on May 4. The last partition is from January (which day depends on the premake value, in this example the 6th), so since pg_partman does not find a partition for the new data it inserts the new data directly into the parent table (reporting_data). This is again fine and and specified in the documentation. However, on the next run_maintenance() run, I would expect partman to find the new data and recognize that it needs to play catch-up with the partitions. It does indeed find the data from the parent (v_max_time_parent), but does not create any new partition tables to account for this.

Debug output from run_maintenance() (but does not create any new partitions):
`
NOTICE:  run_maint: parent_table: public.reporting_data, v_last_partition: reporting_data_p2016_01_06
NOTICE:  run_maint: v_current_partition_timestamp: <NULL>, v_max_time_parent: 2016-05-04 20:00:00
`

So, I'm wondering if it is possible to create these needed partitions based on data in parent? Currently we manually look out for this and insert bogus data into the last existing partition, then run maintenance which THEN creates partitions up to the parent table's newest data. 

And, as a follow-up question, is it possible to exclude the "intermediate" partitions when there is no data for them? e.g. in the above example create no tables from Jan 7 to May 3, and make partitions for May 4 (reporting_data_p2016_05_04) onwards as needed?

Tried to make the example as simple as possible but please let me know if it's not clear and/or if you'd like some more info.

Thanks,
Kayvon

PS the pg_partman extension is dope, very valuable tool for us to have here that makes managing our db setup much easier! Thanks for the hard work!

**Comment by keithf4** [comment]
I recognized this issue so that's why I added the `infinite_time_partitions` column in the `part_config{_sub}` in version 2.3.0. By default this is false, and will act as you saw. Setting it to true will cause it to continue creating time based tables even if no new data is added. I know you don't want the intervening empty tables, but trying to account for that in a general case would be adding more complexity that I don't want to do at this time. Unless you're going to have thousands of child tables, it shouldn't affect anything. If it does start to, I'd recommend something that goes back and culls empty child tables after a certain time.

I don't want to have pg_partman create any tables based on data existing in the parent because the basic model of how I assume things will work is based on that table being empty. It's why I provide the `check_parent()` function to monitor for this and respond quickly to fix it. The easiest way to fix this if data goes into the parent is to just run the `partition_data_time()` function and that will move any data from the parent and create the necessary children (or use the python function if it's a lot of data to batch it). Shouldn't need to insert any bogus data to fix this.

So a quick summary of ways to fix this:

1) Leave `infinite_time_partitions` as false to not create a bunch of empty tables. Use `check_parent()` to watch for data going into the parent function. Run `partition_data_time()` to move the data out and create new child tables. Once new child tables are created, `run_maintenance()` should start working again properly.

2) Set `infinite_time_partitions` to true to continue creating all child tables even with no new data. If there are a lot of empty child tables causing an issue, create something that can drop them.

Hope that helps.

**Comment by kayvonr** [comment]
Thanks so much for the quick reply - I had overlooked both these functions! 

About culling empty child tables - is there a special procedure to do this? or simply just issue a DROP TABLE command?

**Comment by keithf4** [comment]
No special procedure. Just make sure you're culling old tables and not the new ones that are premade (which will likely be empty as well). Some functions that might be useful in determining which to drop:

`show_partitions()` will list all child tables in a partition set in logical order (ASC or DESC).

`show_partition_info()` if given a child table, can tell you the upper & lower boundaries for the data of that table. Might be useful in determining which are older than a certain time period that you want dropped.

Both these functions can be queried as tables (SELECT * FROM ...) to return rows with named columns for easy filtering and comparison.

Glad to hear things are working good for you! :)

**Comment by kayvonr** [comment]
Great, just wanted to make sure there was not an extra step needed in removing tables. And the `partition_data_time()` function worked out great and removed a lot of headache, thank you for that. 

Thanks again for this extension, it's pretty great and we're pretty big fans!
