### ISSUE TITLE
Error applying constraints - "because it is being used by active queries in this session"

### ISSUE THREAD

**Issue by broseed** [keithf4/pg_partman#126]
Hi - great extension! Excited to start using it, but have run into an issue:

Postgresql 9.5.1
pg_partman v2.4.0

I've setup id partitioning.  For proof of concept, I setup 5k row partitions with a max of 50k configured to drop extra tables.  Additionally, I have added some constraint cols to the create_parent call.  I've attached a dump of my part_config table (part_config.txt) as well as the error log from postgres (error.txt).

These tables are read only after insert.

If I remove the constraints from the table, the partitioning works fine.  Have I set something up wrong?  Let me know if you need more information.

Thanks,
Dylan
[error.txt](https://github.com/keithf4/pg_partman/files/337601/error.txt)

[part_config.txt](https://github.com/keithf4/pg_partman/files/337603/part_config.txt)

**Comment by keithf4** [comment]
Are you running into this error when you call create_parent() or at some point later? The error you've included seems to hint at the problem
```
cannot ALTER TABLE "call_p0" because it is being used by active queries in this session
```
Are you doing something else to the table at the time you're trying to partition it?

**Comment by broseed** [comment]
The create_parent() call completes successfully. It seems to happen only when the extension determines it's time to apply the additional constraints on the older partitions. I just verified that the only thing happening at the time of error is an attempted insert into the parent table (which fails due to this error).

**Comment by keithf4** [comment]
Actually, searching around I may have found the issue

http://stackoverflow.com/questions/15961183/postgres-partition-management-with-triggers-issue-altering-tables

You're doing ID partitioning and are using the default means of creating new partitions where it will try and make a new table when it reaches 50% of the current one. This also kicks off the process that will apply constraints to older tables. From what I'm reading this shouldn't break unless it's somehow trying to apply the constraint the the current table that the trigger ran from. I noticed you may have `optimize_constraint` set to 1 (it's hard to tell since you did a dump and I can't tell which columns go with which values, but the default ordering looks to align with that). 

Can you try setting `optimize_constraint` to a higher value so it's not trying to alter the current table?

**Comment by broseed** [comment]
I set the optimize_constraint to 10 instead of 1 and am still seeing an error unfortunately.  I've attached images of the configuration settings in the db. Let me know how else I can help.  Thanks.

![screen shot 2016-06-28 at 10 39 35 am](https://cloud.githubusercontent.com/assets/838728/16426308/4b2fa5b6-3d1d-11e6-8fd9-93d7eb61e964.png)
![screen shot 2016-06-28 at 10 39 26 am](https://cloud.githubusercontent.com/assets/838728/16426307/4b2f8b94-3d1d-11e6-84e3-7eff946757d2.png)

**Comment by keithf4** [comment]
Are you absolutely sure that the INSERT statement is not inserting to any child tables that would be having their constraint applied? Any chance you could give me a schema and list of commands you've run to reproduce this error? Having trouble recreating the situation to trigger this issue here.

**Comment by broseed** [comment]
I think I see the issue.  My insert statement uses a CTE to query the table we're inserting into to see what already hasn't been processed. I'm guessing that is causing the problem.  Here is an example to reproduce ({} are variables):

**INSERT INTO {table} ( 
{col1}
)
with {cte} as (
	select {col1} from {table} limit 1
)
select {col1} from {cte}** 

Hopefully that will help you reproduce.  Let me know if not.

Thanks.

**Comment by keithf4** [comment]
Only way to handle that is to avoid using the trigger to perform partition maintenance. You can set `use_run_maintenance` to false for the partition sets that need to do this and then schedule maintenance to run often enough to keep up with your ingestion rate. 

You'll have to recreate the trigger function to take out the maintenance code for these tables either by undoing and redoing the partitioning or just calling `create_function_id('schema.table')` directly.

**Comment by broseed** [comment]
>>You can set use_run_maintenance to false for the partition sets that need to do this and then schedule maintenance to run often enough to keep up with your ingestion rate.

Do you mean that I should set `use_run_maintenance` to `true`?  It is currently set to false which, I believe, means to not use the BGW for maintenance.

Is running that maintenance every 10 minutes unreasonable?

**Comment by keithf4** [comment]
Sorry, yeah. Set it to true.

Reasonable has to be determined by your ingestion rate. As long as it's creating new partitions faster than your data is getting inserted, you should be fine. If you are actually having to run it that often to keep up though, may want to see about making the pre-check larger and run it less frequently. Keep in mind that by default, maintenance runs an analyze on any partition set that it creates a new child table on. If there's a larger partition set, this can make maintenance take a bit. You can set the maintenance to not run those analyzes (either as a flag to `run_maintenance()` or by setting it in postgreql.conf if using the BGW), but then you'll have to schedule something that runs it manually some other way. Otherwise, constraint exclusion may not work efficiently.

**Comment by broseed** [comment]
Understood - thanks alot.
