### ISSUE TITLE
Question: partition sizes.

### ISSUE THREAD

**Issue by MikaelUlvesjo** [keithf4/pg_partman#129]
Is there a recommended partition size in form of nr of rows/partition and a recommended maximum number of partitions?

We have a system where we add about 200 rows/sec in a table with 8 columns ( bigint, integer, double, smallint and one geometry from postgis ) , we have to save data for 2 years.

We use id partitioning on a bigint column that stores epoch in milliseconds.

The current setup we have the partition interval set to "172800000" that is 2 days, so after two years we will have about 365 partitions with data, and every partition will have about 34.5 million rows. 

Do we have to large partitions or to many partitions?

Can you recommend a partition size for us?

**Comment by keithf4** [comment]
Honestly, the size of your partitions is what works for you. The thing to do is evaluate the query plans against your partition tables and if it seems like they're taking too long to even do an index scan on the tables that are not excluded, then you may want to consider making the interval smaller.

We've got a daily partitioned table going back to 2007 and as of today has 3399 tables and it works perfectly fine. When querying partition sets with a lot of tables, it's really about how many are being scanned within a single transaction run. If constraint exclusion is able to eliminate most of them, it's generally not a problem. If not, you may need to adjust `max_locks_per_transaction` as I advise for running the pgTAP tests since it touches many tables in a single transaction.

When you start getting into the really high numbers of partitions (tens of thousands) constraint exclusion helps, but even then it can get bogged down since the planner still has to check the constraints of each child table to actually exclude it. If you're running into this, and can't drop tables, it's best to adjust your application to directly query the child tables instead of relying on constraint exclusion. That's when having a predictable naming pattern really helps.

Also, queries against the catalogs (anything touching `pg_class` or `pg_attributes` especially) can start taking longer so you may get performance issues on what are typically simple monitoring queries or queries to get table statistics. If this begins to become an issue, that's when I would start being concerned you have too many partitions. Then you should re-evaluate your partitioning intervals and whether you really need to keep all that data live in the system. That's the main reason I included the retention system and a script to reliably dump out old partitions so you can just keep that data available offline and load as needed.

**Comment by keithf4** [comment]
Also, speaking of the system catalogs, if you do end up using the retention system to clean up old tables, then you can run into bloating the system catalog tables. I've been working on another bloat checking script that helps with just that issue.

https://github.com/keithf4/pg_bloat_check

**Comment by MikaelUlvesjo** [comment]
How do I change the partitioning interval?

**Comment by keithf4** [comment]
Unfortunately there's no easy way built in currently and it's something I'm working on. You can change the interval in the config table, but then for maintenance to automatically pick up on that, you'd have to change the partition suffixes of the tables to reflect the new interval pattern. The renaming can be done using the same methods I outline in the migration document when moving from a completely different partitioning system to pg_partman.

**Comment by keithf4** [comment]
If you're not editing old data, you technically wouldn't have to adjust the constraints unless you were making the interval larger. But that would be something to look at changing at least for the most recent tables.

**Comment by MikaelUlvesjo** [comment]
If I change the interval from 48 hours to anything that is evenly multiplied to 48 then the table names would be correct but with gaps. 

So if I change from 48 hours to let's say 12 hours, then the old tables would still be found by the maintenance job, but containing 4 times the data it should and 3/4 of the tables would be missing, would the maintenance job create the missing tables and move the data to the correct table?

**Comment by keithf4** [comment]
I believe a 48 hour interval would use the daily partitioning scheme, but a 12 hour interval would use the hourly scheme, so you'd have to do some renaming there. If you went from 48 hrs to 24 hrs that would keep the daily naming scheme.

Maintenance never backfills tables before the newest one nor does it ever move data.

**Comment by MikaelUlvesjo** [comment]
I don't think that as I'm using the id partitioning, and the column I'm partitioning on is a bigint and just happen to store an epoch timestamp in ms.

**Comment by keithf4** [comment]
Oh, I thought you were using the built in epoch partitioning method. Yeah things should be fine then, although the name of the table may not be accurate as to what the lower limit of that table is anymore.

**Comment by MikaelUlvesjo** [comment]
**Hi**

We now have more data in our database, so we have about 4500 partitions and now the system is starting to be too slow, I have implemented a workaround that uses the partitions directly and that solves the problem, as you can see in the analyze result below almost all time is spent planning the query.
Is there a way to optimize the planning?
Constraint exclusion is working as you can see.
We need to have total time below 50ms.

```
"Unique  (cost=35.07..35.08 rows=2 width=74) (actual time=2.141..2.203 rows=99 loops=1)"
"  ->  Sort  (cost=35.07..35.07 rows=2 width=74) (actual time=2.139..2.149 rows=325 loops=1)"
"        Sort Key: data_table.id, data_table.source"
"        Sort Method: quicksort  Memory: 70kB"
"        ->  Append  (cost=0.00..35.06 rows=2 width=74) (actual time=0.050..2.033 rows=325 loops=1)"
"              ->  Seq Scan on data_table  (cost=0.00..0.00 rows=1 width=74) (actual time=0.001..0.001 rows=0 loops=1)"
"                    Filter: (("timestamp" >= '1479700545411'::bigint) AND ("timestamp" <= '1479700605411'::bigint) AND (location && '0103000020E61000000100000005000000B4EFBED33F1 (...)"
"              ->  Index Scan using data_table_p1479693600000_pkey on data_table_p1479693600000  (cost=0.42..35.06 rows=1 width=74) (actual time=0.049..2.017 rows=325 loops=1)"
"                    Index Cond: ((source = ANY ('{1,2,3,4,5,6,7}'::integer[])) AND ("timestamp" >= '1479700545411'::bigint) AND ("timestamp" <= '1479700605411'::bigint))"
"                    Filter: (location && '0103000020E61000000100000005000000B4EFBED33F1 (...)'::geometry)"
"                    Rows Removed by Filter: 3130"
"Planning time: 530.954 ms"
"Execution time: 2.394 ms"
```

**Comment by keithf4** [comment]
Is that the entire query plan? The individual times I see don't total up to anything near 530ms, so it's hard to say what the problem or solution could be.

**Comment by MikaelUlvesjo** [comment]
That is the entire query plan, so what takes time is to create this query
plan the actual execution of it is just a few ms.

Den 21 nov. 2016 5:30 em skrev "Keith Fiske" <notifications@github.com>:

**Comment by keithf4** [comment]
My apologies, completely missed that. So, as I said in the original response, when the planning of constraint exclusion starts to have an impact like this, you may have to either start dropping partitions or see about repartitioning to a larger interval. If querying the children directly solves it, then that is most likely your issue. A sub 50ms response time on a 4000+ inheritance set I think is starting to push your CPU's limits.
