### ISSUE TITLE
Create partition tables for specific ranges after create_parent is called

### ISSUE THREAD

**Issue by ykim** [keithf4/pg_partman#130]
Is there a script or function to create partition tables for new ranges after create_parent is called? As an example, I currently have a table partitioned by id, where the created partitions range from 2000000 to 4000000 (in intervals of 100000). I'm planning on populating the range from 0 to 2000000 later, but it'd be nice to be able to pre-create the partition for this range instead of migrating then calling partition_data.py.

**Comment by keithf4** [comment]
Currently, no. It creates partitions based on the data that is there and maintenance doesn't ever create any partitions older than the newest one.

You can create the child tables manually yourself and, as long as you've following the standard naming pattern, it should be fine. The trigger function may fall back to the dynamic portion, though, which is a lot less efficient and not ideal for larger data loads. So, depending how much data it is, you may be better off either inserting directly to those child tables or doing using partition_data.py anyway.

**Comment by ykim** [comment]
That makes sense. I brought this up because when partition_data.py is used to partition the parent table, any new table created seems to lock up queries to the parent table. Is this something that is configurable when partiation_data.py is ran?

**Comment by keithf4** [comment]
It's doing a SELECT FOR UPDATE to ensure the being moved is not locked and in use already. So if you have something that is querying that data that was in the parent, it will cause a lock. You can try making the block of data being moved smaller to minimize that lock.

**Comment by keithf4** [comment]
If forgot, there is an option `--lock_wait` for the partition_data.py function. While this won't stop it from locking data itself, it will put a limit on how long it will wait to try and obtain the lock if the data is already locked by another application.

If your issue is with the partitioning script itself, locking the data, making a smaller batch size for the script should help to limit this. The python script commits after each batch runs, so the SELECT FOR UPDATE should only hold a lock for the amount of time it takes that batch to commit.

**Comment by keithf4** [comment]
The script also turns autovacuum on and off. This does require a lock at the beginning and at the end for all tables in the partition set since it runs an ALTER TABLE. But as soon as the ALTER commits, it should release the lock.

You can disable this feature with the `--autovacuum_on` option to partition_data.py. Be aware that if you're moving a lot of data, autovacuum may keep kicking on cause additional I/O.
