### ISSUE TITLE
How to measure performance effect of N partitions managed by pg_partman

### ISSUE THREAD

**Issue by luiscape** [keithf4/pg_partman#134]
I am wondering how can one measure the impact of having N partitions (created and managed by pg_partman) in the ingestion process of data into a database. I am currently working with around 100 billion records organized across a year. To improve query performance, I am using `pg_partman` for creating and managing partitions (one per day). However, I would like to measure what is the impact on performance for ingesting those records (from csv files using `COPY`). Any way I can do that?

**Comment by keithf4** [comment]
I believe data ingestion performance should be measurable by just general load testing by inserting records. Not aware of any special tests that would show it's impact as the number of partitions increases since each insert is generally only going to be going to a single partition at a time. There is a pretty significant hit to write performance with trigger based replication and there's not much to be done about that until some sort of partitioning method is built into PG.

What I generally recommend to people doing significant data ingestion into partitioned tables in postgres is to insert directly into the children. If the child tables have a predictable naming pattern (which pg_partman does), it should be fairly easy to have the data ingestion process dynamically figure that out based on the data values themselves. If the child table does not exist, that can be an issue, and checking for existence each time before insertion could add overhead. But if the child tables should always exist for new data coming in, that can significantly speed things up.

**Comment by luiscape** [comment]
@keithf4 thank you for your feedback. We were wondering about that idea and wanted to ask you in another issue if that sounded reasonable. This question has been answered perfectly -- closing this issue. 

We will go ahead and implement a partition-specific series of COPY statement.
