### ISSUE TITLE
Does turning off index updates on parent tables also turns off in child tables?

### ISSUE THREAD

**Issue by luiscape** [keithf4/pg_partman#135]
Based on the use-case of a previously closed issue (#134)--in which we are ingestion billions of rows to a partitioned table--we are now implementing the suggested solution of making `COPY` statements directly to the child tables instead of the parent table. 

One of the performance-enhancing methods we use is to turn-off index computation until the ingestion process is complete. The technique includes changing the property `indisvalid` to `FALSE` and then turning it back to `TRUE` after the process is complete (and also running `VACUUM ANALYZE`). We have followed the PostgreSQL documentation (link [here](https://www.postgresql.org/docs/current/static/catalog-pg-index.html) to implement that process). 

We do that by performing the following query:

```sql
UPDATE pg_index
    SET indisvalid=FALSE
    WHERE indexrelid IN ('{value}'::regclass);
```

Where `{value}` would be the name of the index. 

However, when dealing with index inheritance between child tables and its parent we were wondering how that process propagates to the child tables. Are they affected by that query above? Is the index effectively not computed on every `COPY` statement? Do child tables wait for that index to be turned on again and run alongside `VACUUM ANALYZE` to trigger index re-calculation?

Thanks a lot!

**Comment by keithf4** [comment]
Can't say for sure since I've never tried this method. I would doubt that propagates since each is a distinct entry in the catalogs and you're editing the catalog directly. I'd just suggest doing some testing and see how it goes. That's what I would have to do in this case. 

Honestly, I'd just drop the index and recreate it after the ingestion process. Directly editing system catalogs is generally not recommended and I'd be curious on the state of the index after doing that and whether a simple REINDEX call would fix it. And if you're having to call REINDEX anyway, it's probably safer to drop/create anyway.

**Comment by keithf4** [comment]
Just re-reading this again and realized you're only doing a vacuum after re-enabling the index. That is not going to ensure that the index is valid anymore and you may be leaving your indexes in a corrupted state. Especially if they're unique or function based since neither of those processes was being run during the data ingestion. I'm honestly not even sure if index entries were being made at all while it was invalid. And vacuuming will not insert those missing entries if so. Unless it was a vacuum full, which just recreates the indexes anyway.

So, again, I'd recommend dropping/creating the index to speed up the ingestion process. Index creation from scratch is far more efficient than index processing during data insertion.

**Comment by luiscape** [comment]
@keithf4 again, really useful comments. When dropping an index on a parent will it also get dropped from its children? Also, when deciding to drop indexes, some of those `DROP` calls may take a significant time to complete. Any suggestions?

Thank you!

**Comment by keithf4** [comment]
Index creation and removal is not propagated. I do have a script in the `bin`  folder to recreate indexes on child tables based on what the parent has, but it does it for all child tables. But by default it only creates indexes if they don't exist and does not recreate them if they do, so could use it to add indexes back after you drop them. Note that it will drop indexes from children if they don't exist on the parent. Can check the code there and may find something useful if you can't use the script itself.

Both the CREATE INDEX & DROP INDEX commands have a CONCURRENTLY option. This causes the index management to not block any other incoming statements. Note this can make index creation take a lot longer on heavily written tables, though. So, it won't speed anything up, but will make it cause less contention. A DROP will only take a long time if there is a currently running transaction on that table. Otherwise, it should be fairly quick.

**Comment by luiscape** [comment]
Ok. Got it. 

To give you a bit more information about our scenario: we have a single PostgreSQL database running that has to ingest about 25 billion records (about 70M / day). The table that holds those records is partitioned based on the `daily` parameter (so one partition per day) and has three B-tree indices.

At first, we need to ingest about 30 days of data. Then on a subsequent run, we'll ingest 10 months of data and, finally when on production, a single day every day. We have more time on our hands for ingesting a single day so we are not worried about that last part. Now, as for the first 30 days ingest and 10 months ingest we have two approaches in mind (base on what you've suggested):

**30 days ingestion:**

- Create db without indices or without being partitioned.
- Ingest data.
- Create indices.
- Partition table using the `create_parent()` function.

**10 month ingestion**:

- DROP indices
- Run /bin script to replicate configuration on child tables.
- Ingest data directly to child tables.
- Recreate indices.
- Run /bin script to replicate configuration on child tables.

Does that sound reasonable? I know this may be outside the scope of this issue, but would really appreciate your input. 

PS: Which one is the script that replicates the configuration from parent to child?

**Comment by keithf4** [comment]
Some misunderstanding here. I said there is a script that can recreate the parent indexes on the child tables, not the configuration in general. It is `reapply_indexes.py`.

So it would go like this

**30 days ingestion:**

- Create table without indices & without being partitioned.
- Ingest data.
- Partition table using the create_parent() function.
- Run reapply_indexes.py to create indexes on children
    
**10 month ingestion:**

- DROP indices on all children that will be getting new data (you'll have to do this yourself somehow, script does not do this)
- Ingest data directly to child tables.
- Run reapply_indexes.py to create indexes on children

Also note that pg_partman does not create child tables on demand during data insertion, nor does it create partitions in the past as part of normal maintenance (it does create a few past partitions when you first partition the parent table). If you need child tables for the last 10 months created, I would suggest using the `p_start_partition` parameter to the create_parent() function. See the doc file for more info on that parameter  https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md#creation-functions

**Comment by luiscape** [comment]
Ok. I think I understand your suggestion -- really appreciate it. 

One last thing, when you say "Run reapply_indexes.py to create indexes on children", does that mean that the function `create_parent()` does not create indexes automatically when a parent table is partitioned and children table are created?

**Comment by keithf4** [comment]
create_parent() does create indexes on the child tables if they exist on the parent. But your goal is to load the initial data faster, so you said you were going to create the parent table without the indexes first.

**Comment by luiscape** [comment]
I see. Now, if I create the index in the parent then run `create_parent()` that index will be replicated. In that case I wouldn't have to run the script `eapply_indexes.py`. Is that right?

**Comment by keithf4** [comment]
Correct. But if your purpose is to speed up the data loading, and was the whole reason I'm assuming you were trying to disable them in the catalogs, it will go faster without the indexes there.

**Comment by luiscape** [comment]
I understand your suggestions. Thank you for the advice. Closing this issue now.
