### ISSUE TITLE
Partitioning by tstzrange

### ISSUE THREAD

**Issue by Trekoid** [keithf4/pg_partman#142]
I'm on a project where range partitioning by the lower bound of a tstzrange column is needed. We plan on implementing by using pg_partman as a basis since lower(tstzrange) = timestampz. Is this a feature that would be desired such that we should contribute it back to the project or is it outside of the scope of the planned roadmap?

**Comment by keithf4** [comment]
pg_partman is centered around partitioning predetermined intervals on a static value column. Adding an option just for lower(tstzrange) is really too narrow a use case for adding that kind of complexity to the trigger generation. If you need something a little more flexible, you could take a look at the range_partition extension I mention in the README.

If you'd like to use pg_partman, another option would be to have another column that is automatically populated with the lower bound of the tstzrange column value via a trigger. You could then partition based on that generated column since it's a static time value. But if the lower value of that range ever changes, that wouldn't work since that could possibly break the constraint and require moving the data to another child table. Something to keep in mind with whatever solution you go with.

**Comment by Trekoid** [comment]
For my use case, lower(tstzrange) is static. We are doing something akin to session logging. The start time is fixed, the end time may extend for a period of time. After 24 hours all records are stale and do not need to be in the active table anymore, so we wanted to have a daily window of active data.

I have looked at range_partition, pg_slice, pg_pathman and pg_partman. The issue all these partition tools have is they work off of a column of type timestamp. In the broadest sense, I am looking to partition off of an expression that evaluates to type timestamp. I haven't found a tool yet that meets this need. I guess adoption of the native PostgreSQL data range types is still in the early upswing.

I considered having the extra column, but I disliked the idea of having duplicate data. There is also the option to break the tstzrange into two columns, an open and a close. However, I lose the easy query syntax—such as the `@>` operator—and most importantly I cannot setup an exclusion constraint to prevent overlapping sessions—`exclude using gist (id_col with =, tstzrange_col with &&)`.

I decided to start with pg_partman as a base as all of the time range partitioning logic is there. I would just need to tweak things a bit to include the lower() function call to extract the relevant timestamp out of the range data type. The trigger function would end up looking something like: 
`       IF TG_OP = 'INSERT' THEN 
            v_partition_timestamp := date_trunc('day', lower(NEW.col3));
            IF lower(NEW.col3) >= '2016-10-27 00:00:00-07' AND lower(NEW.col3) < '2016-10-28 00:00:00-07' THEN 
                INSERT INTO test.part_range_p2016_10_27 VALUES (NEW.*) ; 
`
Something similar would be done to the check constraints.
`CHECK (lower(col3) >= '2016-10-29 00:00:00-07' AND lower(col3) < '2016-10-30 00:00:00-07')`

I am going to have to maintain an internal fork regardless, as our organization has some custom table logging we would want every partition to have, so we'll just keep it in house for now.
