### ISSUE TITLE
Creating new child partitions

### ISSUE THREAD

**Issue by AveshCSingh** [keithf4/pg_partman#174]
I see from #161 that create_partition_id can be used to create new child partitions, and see from your v3 documentation the function spec.

But it seems that when you create a child partition in the prosrc function, you also call create_function_id and apply_constraints, as is done here: https://github.com/keithf4/pg_partman/blob/93bab93dd072c11bfd502ebf1a9a62b29fab89da/sql/functions/create_function_id.sql#L246

Must these two functions also be called when creating a child table?

**Comment by keithf4** [comment]
apply_constraints() is already called within the create_partition_id/time() functions. create_function_id/time() is not since it may not be relevant. Generally when maintenance calls create_partition* it's doing so to create new partitions to catch up to current and then recreating the partitioning function is required. I'll see about adding a note to the documentation that create_function may need to be called depending on the intervals given. Thanks!

Also, the section of code you highlighted is actually being deprecated in 3.0. That created code in the partitioning trigger to automatically make new partitions when the current one reached 50%. Calling DDL on the fly based on data insertion has subtle issues, especially with high concurrency. It's also a bit of a pain to maintain that code. See the CHANGELOG for 3.0 for more info.

**Comment by AveshCSingh** [comment]
This is very useful, thanks Keith. I've successfully created child shards in a matter of seconds on our production DB instance.

Your point on high concurrency issues is insightful. We actually experienced an outage last week because many writers were concurrently trying to create a new child partition, each requesting a lock on the table. I agree with your decision to deprecate the automatic partition creation code.

Thank you!
