### ISSUE TITLE
Fix time trigger function maintenance to be based on data in partition instead of CURRENT_TIMESTAMP (Was: Improved trigger function table caching)

### ISSUE THREAD

**Issue by AveshCSingh** [keithf4/pg_partman#176]
The functions create_function_id and create_function_time generate a trigger function which includes a set of if-then branches to quickly find the correct child table without requiring a query on pg_catalog.pg_tables. I refer to this as caching.

The logic to generate elements in this cache is to take the child with largest timestamp/id, and include this child as well as n previous tables in the cache. This logic is broken when child partitions are pre-created, as they must be beginning in v3.0 (as auto partitioning is being deprecated).

I have a few suggestions on improving this function:
(a) Implement something like an LRU cache
(b) Use the timestamp most close to the current epoch for create_funciton_time's epoch.

**Comment by keithf4** [comment]
Not sure I follow what you're trying to do here, or where it's broken. Serial partitioning creates its list of if-then branches based on the current maximum value in the table. Time partitioning creates its list based on the CURRENT_TIMESTAMP value at the time it's called. And actually, now that I think about the time-based ones, calling create_function_time() could potentially break if it's called and maintenance hasn't created the proper child tables. Time partitioning should be basing it on the max value in the partition set as well. The if-then list is making an assumption that all tables it uses exist without having to do a catalog lookup. Making a note to look into this further. 

Child tables don't have to be pre-created as partitioned when you're doing non-native partitioning. It's easy to simple recreate the old child table as a parent, same as the original parent table was. For native partitioning, yes the child tables must be pre-declared as partitioned, but the trigger function is irrelevant for native partitioning since it doesn't exist. Doing something like an LRU seems overly complicated at this point with native on its way in.

**Comment by AveshCSingh** [comment]
My mistake --I hadn't realized that time paritioning creates is list based on the CURRENT_TIMESTAMP. We're using serial partitioning, and while I'd glanced over the create_function_time function, I hadn't actually tried it.

What do you mean by native vs non-native partitioning? I can't find these terms in the Readme, and so don't follow your second paragraph.

**Comment by keithf4** [comment]
Since you mentioned v3.0 of pg_partman, I assumed you'd read over the CHANGELOG for it. That version incorporates native partitioning which will be included in PostgreSQL 10

https://www.keithf4.com/postgresql-10-built-in-partitioning/

New child tables will still be premade in v3.0 without the automatic code in the trigger function. You just have to run maintenance often enough, and set the premake high enough, to keep up with your data ingestion rate.

**Comment by AveshCSingh** [comment]
Oh, that's great news! I'm not going to worry about optimizing the serial trigger function, as this will be disappearing in pg-partman v3.0 / pg v10.

**Comment by keithf4** [comment]
I'm going to leave this one open so I remember to review the trigger code for timing. Thanks.

**Comment by AveshCSingh** [comment]
Yes! Thanks Keith!
