### ISSUE TITLE
insert with return id does not work

### ISSUE THREAD

**Issue by chrispassas** [keithf4/pg_partman#18]
Example:

insert into example_table (field1,field2) values(1,1) returning id;

Normally in postgresql this will return the ID of the inserted row.  On my tables using pg_partman extension I don't get the ID back.  I'm using an ORM which is basically breaking because this is unexpected for a postgresql database.

**Comment by bsebi** [comment]
What about the following solutions:

Solution 1:
1. Configure partman trigger to return NEW
2. Add an after trigger on the parent table(as suggested in the stackoverflow post) where the entry is deleted from the parent only if it exists in the child.

Solution 2:
1. Configure partman trigger to return NEW
2. Create a view that selects everything from the parent table
3. Move the trigger from the parent table to the view, but as an INSTEAD OF trigger

Problems:

Solution 1 - if the trigger is not dropped i think it may affect the unpartitioning.
Solution 2 - row will never be added to the parent table

Are there any other issues that you can think of? What about performance between the two?

**Comment by keithf4** [comment]
This problem has been solved with native partitioning in PostgreSQL 10: RETURNING again works like a "normal" table. 

At this point, if this is something critical to your infrastructure design, then it's far better to get upgraded to 10 than to try and engineer a work-around for older versions. pg_partman has support for 10 as well, so that will be my "fix" for this issue for the foreseeable future.

**Comment by bsebi** [comment]
Unfortunately the database is already partitioned using pg_partman 3.x and PostgreSQL 9.5. It took a week for the operation of partitioning on a table having 2.4 billion records.

My question is: Do you see any problem with solution 1? Or with solution 2? What is the easiest way to upgrade from 9.5 to 10 having pg_partman already set up with partition type partman? Is there a way which does not involve un partitioning?

**Comment by keithf4** [comment]
You can upgrade to 10 and still use the old partitioning methods in 10 until you're ready to migrate to native partitioning. You should also be able to change from trigger-based partitioning to native without having to re-partition things. 

1. Uninherit the child tables. If you use the `undo_partition_*()` function in pg_partman, by default it only does an uninherit, so that could at least automate that part and remove its trigger function and config data. 
1. Recreate the parent table since you cannot change a normal table into a partitioned one. Can do that with some renaming to get things swapped around. 
1. Reattach the children with the new sql synatx (ALTER TABLE ... ATTACH PARTITION ... FOR VALUES ...). You'll have to do this for every child table.
1. Run `create_partition()` again but telling it to be native. It should see you already have the necessary child tables done so may thrown some warnings, but should work to get the partition management back in pg_partman. Note that currently PG10 does not support index & foreign key inheritance, so it uses a template table (created automatically) that you create the indexes you want the children to have. Check the `part_config` table for the name of the template table.

I would **_highly_** recommend testing this process first. I do have plans to include a function to do this migration automatically, but I'm not sure when I'll have the time to get it done. Writing the steps involved above is definitely something I've been meaning to get done, so there's some work done, but I have not tested this yet.

For you solution 1, that's just a rather expensive operation. Each and every write to the table will be done twice (child and parent) and then a lookup will have to be done to see if it can be removed from the parent. If this isn't all done in a single transaction, you will have duplicate data visible for a period of time. All triggers run in a single transaction, so if you go that way, it should be fine. If your write rate isn't very high, this might be ok, but if it's even slightly heavy, this method will greatly amplify the performance degradation. 

Really not sure on solution 2. Seems overly complicated and I'd have to test it out to see if it would even work. And again, the added complexity will add performance degradation to every write in some manner.

So again, my recommendation would be to up your time to upgrading to pg10 and getting native partitioning working. Anything you're doing to older versions is only a temporary fix in the long run and will never be as good and simple as being able to use RETURNING.

**Comment by keithf4** [comment]
Just a note to say that I updated my Step 1 above to say to NOT use `undo_partition_*()`.

**Comment by bsebi** [comment]
PostgresSQL documentation suggest that for major releases, dumping and reloading the database is a must. In this case going from 9.5 to 10 would imply data move, which in the case of my database it is an expensive operation that I do not afford at the moment.

Thank you for your answer, it will be useful for the upgrade for our second postgres database which also has this problem(Django expects RETURNING).

`CREATE OR REPLACE FUNCTION trg_asymmetricdata_after_insert()
RETURNS trigger AS
$func$
	DECLARE
        	v_trigger_exists            bool;
                v_trig_name                 text;
                v_count                     int;
                v_partition_interval        int;
                v_current_partition_id      bigint;
                v_current_partition_name    text;
        BEGIN
                SELECT partition_interval INTO v_partition_interval FROM partman.part_config;
                IF v_partition_interval > 0 THEN
                	v_current_partition_id := NEW.patient_id - (NEW.patient_id % v_partition_interval);
                        v_current_partition_name := partman.check_name_length('parent_table', v_current_partition_id::text, TRUE);
                        SELECT count(*) INTO v_count FROM pg_catalog.pg_tables WHERE schemaname = 'public'::name AND tablename = v_current_partition_name::name;
                        v_trig_name := partman.check_name_length(p_object_name := 'parent_table', p_suffix := '_part_trig');
                        v_trigger_exists := EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname = v_trig_name);
                        IF v_count > 0 AND v_trigger_exists THEN
                        	DELETE FROM ONLY public.parent_table WHERE id = NEW.id;
                        END IF;
                END IF;
                RETURN NULL;
        END
$func$ LANGUAGE plpgsql;`

This is the code I use for the after trigger. The checks are done on small tables(pg_trigger & pg_tables) and the delete also should be done on a small table. I do understand that this will decrease performance. At the moment I rely on the fact that the tables I am doing the extra operations are very small. I will have to benchmark properly.

**Comment by keithf4** [comment]
As long at the performance penalty is not a problem, using those methods should be fine. Also just be aware that in addition to BEFORE triggers firing before AFTER ones, triggers also fire in alphabetical order, so just be careful if you're adding anymore to the parent table.

Not sure where you're reading that in more modern docs but, barring very specific issues that require a dump/restore, `pg_upgrade` is a perfectly good method for upgrading, especially with very large databases. I've upgraded a 1.2TB database in under 1 hr using it. The pg_upgrade itself took less than 1 minute using the `--link (-k)` option, but you also have to re-analyze the entire cluster to get the statistics back and that took another 30 minutes or so. Also recommend having a streaming slave in place to failover to in case the upgrade has any issues.

**Comment by jayarjo** [comment]
@keithf4 could you please elaborate a bit on:

> This problem has been solved with native partitioning in PostgreSQL 10: RETURNING again works like a "normal" table. 

Was `RETURNING` working in some other way prior to verison 10? Is it documented throughly somewhere?

**Comment by keithf4** [comment]
Prior to 10, partitioning was based on inheritance & triggers. RETURNING would not work in most cases since it was basing the RETURNING value on what was being written to the parent table, not the child table the data got redirected to.

If you instead changed the trigger function to also still RETURN NEW at the end, then RETURNING would work. But then that also means you wrote that data to both the child and the parent, potentially duplicating data unless you had some other trigger firing to handle it differently.

Native partitioning fixed this so that writes to the parent allow RETURNING to work/

**Comment by RomanSmir** [comment]
_part_trig_func returning null
