### ISSUE TITLE
Doing upserts with a where clause failing

### ISSUE THREAD

**Issue by wallydrag** [keithf4/pg_partman#184]
I have a use case of creating child tables based on time partition and doing upserts on them based on some condition. 

Here is a sample of what I did
- created the table
 
`create table farji(some_time timestamp not null, name varchar, game int, PRIMARY KEY(some_time, name));`

- ran create_parent on it and setting `p_upsert` so that it appends it to every insert query

`select partman.create_parent('public.farji', 'some_time', 'partman', 'daily', NULL, 4, 'on', NULL, true, 'none', 'ON CONFLICT (some_time, name) DO UPDATE SET (game)=(EXCLUDED.game) WHERE farji.game < EXCLUDED.game');`

- Now when i run insertions, i get following error
`ERROR:  missing FROM-clause entry for table "farji"`
`LINE 1: ... name) DO UPDATE SET (game)=(EXCLUDED.game) WHERE farji.game...`
                                                             ^
`QUERY:  INSERT INTO public.farji1_p2017_05_11 VALUES (NEW.*) ON CONFLICT (some_time, name) DO UPDATE SET (game)=(EXCLUDED.game) WHERE farji.game < EXCLUDED.game`

`CONTEXT:  PL/pgSQL function farji1_part_trig_func() line 14 at SQL statement`

My understanding as of now is that partman is not able to resolve the `where` clause in `p_upsert`.

Is there anyway to get this running? 
Thanks

**Comment by keithf4** [comment]
Honestly, not sure this can be handled with trigger based partitioning in the generic manner that pg_partman creates the trigger function. The problem is the individual INSERT statements in the trigger are targeting the child tables, but your where condition is referencing the parent table. There's no way for the planner to resolve this. You'd have to hard-code the specific child table for each WHERE condition in each INSERT statement in the trigger code. And this would have to change every time you added a new partition, the same way the normal INSERT statement does.

Unfortunately for this particular UPSERT, you'll likely have to wait for native partitioning, and for it to support UPSERT as well. Or you'll have to write your own trigger code generation function to handle this condition.

Will leave this issue open for a while to see if anyone else can think of a solution for it.

**Comment by keithf4** [comment]
At this time, I don't expect this to be supported with trigger based partitioning. It will have to wait for the native partitioning feature to support UPSERT in the future.
