### ISSUE TITLE
Question: Creating indexes on the partitions with native partitioning

### ISSUE THREAD

**Issue by onderkalaci** [keithf4/pg_partman#190]
The following is obviously not allowed by Postgres:

```SQL

CREATE TABLE test.part_test_native (col1 serial, col2 text, col3 timestamptz NOT NULL DEFAULT now()) PARTITION BY RANGE (col3);

CREATE INDEX i1 ON test.part_test_native (col2);
ERROR:  cannot create index on partitioned table "part_test"

-- since we couldn't create the index on the parent table, partitions wouldn't have the index
SELECT partman.create_parent('test.part_test_native', 'col3', 'native', 'daily');

\d test.part_test_native_p2017_06_08
                                   Table "test.part_test_native_p2017_06_08"
 Column |           Type           | Collation | Nullable |                       Default                       
--------+--------------------------+-----------+----------+-----------------------------------------------------
 col1   | integer                  |           | not null | nextval('test.part_test_native_col1_seq'::regclass)
 col2   | text                     |           |          | 
 col3   | timestamp with time zone |           | not null | now()
Partition of: test.part_test_native FOR VALUES FROM ('2017-06-08 00:00:00+03') TO ('2017-06-09 00:00:00+03')


```

Still, I'm curious about creating indexes on `native` partitioning. How are we supposed to create indexes on the partitions with pg 10 indexes?

Thanks!

**Comment by keithf4** [comment]
Long term, I know it will be supported in core at some point. My plan for 10 is to have a template table available that you create all your indexes & foreign keys on.

**Comment by onderkalaci** [comment]
The follow-up question: Can we do `CREATE INDEX CONCURRENTLY` if we're to have a template table?

The question arises because I couldn't find any information in catalog tables about whether the index is created concurrently or not. 

Do you have any plans for that?

**Comment by keithf4** [comment]
Whether an index is created concurrently isn't stored in the catalogs. The concurrently flag to the CREATE INDEX command is just a method for creating the index without a long term lock and once it's created, there's nothing different from it than if it had been created non-concurrently. See the link below for more info

https://www.postgresql.org/docs/9.6/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY

Index creation will be done at the time that the new child table is created, just as it is done now, so there's no need for the concurrent flag as part of normal maintenance. If you're talking about going back and adding indexes later, that would be what the recreate_index.py python script is for and that does have options for concurrent creation since you're likely doing it on tables with data.
