### ISSUE TITLE
Partition column null

### ISSUE THREAD

**Issue by codingPF** [keithf4/pg_partman#192]
I think this is a feature request...

In some rare cases we have an empty partition column. It is a quality issue but why shouldnt we keep these records for later checking....

what about beeing able to have null paritions?
From a technical point that should be doable?

**Comment by keithf4** [comment]
I can't foresee where the partition column itself being NULL would work, especially for time and serial partitioning which is what pg_partman is based around. For time, just have a default of now() and for serial use a sequence so you never run into not having a value. Updates to route data between child tables are not supported, so if it's something you'd update at a later time, that still would not work.

This is also not supported at all in native partitioning in 10 I don't believe. If it's a known quality issue, I'd advise fixing that since a NULL partition value isn't likely to be a well supported feature long term.
