### ISSUE TITLE
Autocreating of Row triggers from template table

### ISSUE THREAD

**Issue by sannek8552** [keithf4/pg_partman#201]
Hello,
Are you going to implement creating row triggers fro template table as well as you do with indexes and foreign keys?

**Comment by keithf4** [comment]
Honestly, probably not. I'd tried doing trigger inheritance prior to 10 and it was a rabbit hole that was hard to crawl out of before and I never found a solution that worked well in a general way that I could support in pg_partman.

I implemented the features I did now with the template table since I didn't want to put off support for native partitioning a whole year. But it was only ever meant as a temporary solution to help people get onto 10 sooner. It looks that 11 may eliminate the need for what the template table provides now, so it will hopefully be going away.
