### ISSUE TITLE
partman.run_maintenance for big table takes a lot of time

### ISSUE THREAD

**Issue by amikhile** [keithf4/pg_partman#207]
HI,

I have noticed that running maintenance on a big tables  takes a lot of time ~ 2 min and during that time the table that holds the foreign key is  locked for updates.
This big table has daily partitions with each ~ 1.5G size.
I want to know if this is a necessary lock down, or it can be avoided. Also why maintenance should lock the foreign key table which is not partitioned?
The maintenance call we use is - SELECT partman.run_maintenance('portal.smr_violations')
So the analyze option is set to true as default, could it be the cause?

we are on postgres 9.6.3 and partman 3.1.0.

```
    Name        | Version  |   Schema
------------+---------+------------
 pg_partman | 3.1.0      | partman

```

part config definition for this specific table:

``
parent_table               | portal.smr_violations
control                    | part_day
partition_type             | partman
partition_interval         | 1 day
constraint_cols            | {transaction_end_time}
premake                    | 3
optimize_trigger           | 4
optimize_constraint        | 2
epoch                      | none
inherit_fk                 | t
retention                  | 120 days
retention_schema           |
retention_keep_table       | f
retention_keep_index       | t
infinite_time_partitions   | t
datetime_string            | YYYY_MM_DD
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             |
``

The big table definition

# \d+ portal.smr_violations
                            
```
 Column        |         Type          | Modifiers | Storage  | Stats target | Description
----------------------+-----------------------+-----------+----------+----------

 transaction_end_time | bigint                | not null  | plain    |
    |
 metric_id            | integer               | not null  | plain    |
    |
 location_id          | integer               | not null  | plain    |
    |
 value                | integer               | not null  | plain    |
    |
 threshold            | integer               | not null  | plain    |
    |
 severity             | integer               | not null  | plain    |
    |
 bucket_start_time    | bigint                | not null  | plain    |
    |
 bucket_end_time      | bigint                | not null  | plain    |
    |
 agent_id             | integer               | not null  | plain    |
    |
 execution_start_time | bigint                | not null  | plain    |
    |
 rule_id              | character varying(64) | not null  | extended |
    |
 event_id             | character varying(64) |           | extended |
    |
 part_day             | date                  | not null  | plain    |
    |
Indexes:
    "smr_violations_pkey" PRIMARY KEY, btree (metric_id, transaction_end_time, l
ocation_id, rule_id)
    "violations_event_id_index" btree (event_id)
    "violations_location_id_index" btree (location_id)
    "violations_transaction_end_time_index" btree (transaction_end_time DESC)
Foreign-key constraints:
    "smr_violations_metric_id_fkey" FOREIGN KEY (metric_id) REFERENCES portal.sy
nthetic_metric_stats(id)
Triggers:
    aa_sync_part_day BEFORE INSERT ON portal.smr_violations FOR EACH ROW EXECUTE
 PROCEDURE portal.smr_violations_sync_part_day()
    smr_violations_part_trig BEFORE INSERT ON portal.smr_violations FOR EACH ROW
 EXECUTE PROCEDURE portal.smr_violations_part_trig_func()

```

Child tables: portal.smr_violations_p2018_01_22,
              portal.smr_violations_p2018_01_23,
              portal.smr_violations_p2018_01_24,
              portal.smr_violations_p2018_01_25,
              portal.smr_violations_p2018_01_26,
              portal.smr_violations_p2018_01_27,
              portal.smr_violations_p2018_01_28,
              portal.smr_violations_p2018_01_29,
              portal.smr_violations_p2018_01_30,
              portal.smr_violations_p2018_01_31,
              portal.smr_violations_p2018_02_01,
              portal.smr_violations_p2018_02_02,
              portal.smr_violations_p2018_02_03,
              portal.smr_violations_p2018_02_04,
              portal.smr_violations_p2018_02_05,
              portal.smr_violations_p2018_02_06,
              portal.smr_violations_p2018_02_07,
              portal.smr_violations_p2018_02_08,
              portal.smr_violations_p2018_02_09,
              portal.smr_violations_p2018_02_10

**Comment by keithf4** [comment]
Yes, it's most likely due to the analyze step. I would recommend turning the analyze off for the run of this table and see how it goes. But then you will have to schedule something to analyze the parent level of the table at some point so that constraint exclusion works efficiently over time. 

When creating the FK, it does have to be validated and since there's no data, normally that would be a very quick lock. Since the maintenance runs entirely as a single transaction all locks that are required to be obtained to create everything are held for the duration. There is currently no way to avoid this situation in trigger-based partitioning unfortunately. PostgreSQL 10 native partitioning avoids a lot of this since the constraint management is all handled internally, so I don't believe the analyze is a required step. Glad you brought this up because I need to double-check that and I may be able to make the analyze false by default for 10. 

Note that 10 currently doesn't have as many features as trigger-based, so recommend checking it over before you upgrade. The only one I haven't accounted for so far in pg_partman is being able to handle data that has no target child. That will be handled in PG11 thankfully as well as handling FKs much better as well.

**Comment by marcocitus** [comment]
+1 on making analyze false the default for native partitioning.

Adding/removing a partition takes an access exclusive lock on the parent table when using native partitioning, which is a regression from using inherited tables, since adding/removing a child takes a share update exclusive lock. Running analyze while holding on to an access exclusive lock is not great.

**Comment by keithf4** [comment]
Thanks for that note @marcocitus 
Forgot about that lock during the add/remove of child tables.

**Comment by amikhile** [comment]
I have tested without the analyze and the run_maintenance execution took 1.3sec.
Do i have to run the analyze as a separate task if we have the autovacuum set to on. 
It is said in documentation that autovacuum will execute an  ANALYZE?

**Comment by keithf4** [comment]
Autovaccuum (and hence auto analyze) runs based an amount of writes to any given table (based on autovacuum_vacuum_scale_factor, autovacuum_analyze_scale_factor, autovacuum_vacuum_threshold,  autovacuum_analyze_threshold). Since the parent table in a partition set should ideally never be getting writes, autovacuum will never kick in on it until it hits autovacuum_freeze_max_age which could take months or years and is usually not ideal to hit often anyway. Therefore a manual analyze of the parent table is required for its statistics to be updated for constraint exclusion to work. You could just schedule a manual call to analyze the database or specific tables at the same time you schedule your maintenance calls if you're not using the internal BGW scheduler. Otherwise, scheduling a daily analyze of your whole database never hurts anything.

I still need to confirm whether this is still the case for native partitioning or if adding a native child partition automatically updates the necessary stats for this.

**Comment by amikhile** [comment]
Ok, thank you.
We will schedule daily analyze.
