### ISSUE TITLE
ERROR:  invalid input syntax for integer: "" CONTEXT: PL/pgSQL function show_partitions(text,text) line 81 at RETURN QUERY

### ISSUE THREAD

**Issue by aysabzevar** [keithf4/pg_partman#209]
We just migrated our data (~800GB) from one PG database to a minor updated version of PG db server.
No surprise partman didn't work. So I deleted all schema, triggers, functions, etc. related to partman and tried to re-create them. I got error that I've never saw before that in previous migrations.
Note that  I executed these command before with no problem.
I read [this readme](https://github.com/keithf4/pg_partman) again but, nothing changed!
Version of **postgresql-9.6** is **9.6.8-1.pgdg80+1** and version of **postgresql-9.6-partman** is **3.1.2-1.pgdg80+1** which are the latest version in the repository.

What is this error for when nothing has changed but a minor version of PG and partman?

```
hm=# CREATE SCHEMA partman;
CREATE SCHEMA
```
```
hm=# CREATE EXTENSION pg_partman SCHEMA partman;
CREATE EXTENSION
```
```
hm=# SELECT partman.create_parent('public.deliveries', 'id', 'partman', '15000000');
ERROR:  invalid input syntax for integer: ""
CONTEXT: PL/pgSQL function show_partitions(text,text) line 81 at RETURN QUERY
SQL statement "SELECT partition_tablename                       FROM partman.show_partitions(p_parent_table, 'DESC') LIMIT 1"
PL/pgSQL function create_function_id(text,bigint) line 102 at SQL statement
SQL statement "SELECT partman.create_function_id(p_parent_table, v_job_id)"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 626 at PERFORM
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_function_id(text,bigint) line 298 at RAISE
SQL statement "SELECT partman.create_function_id(p_parent_table, v_job_id)"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 626 at PERFORM
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 670 at RAISE

```

**Comment by keithf4** [comment]
Can you share the schema for the table you're trying to partition? Just typing `\d+` in psql should be good enough.

**Comment by aysabzevar** [comment]
@keithf4 

Here it is!
[hm-deliveries-schema.txt](https://github.com/keithf4/pg_partman/files/1799598/hm-deliveries-schema.txt)

**Comment by keithf4** [comment]
So, I had 9.6.6 installed and I made a table with just the partition column in the schema you gave and things worked fine. I upgraded to 9.6.8 and tried and things worked fine again.
```
keith@keith=# create table deliveries (id bigint not null);
CREATE TABLE
Time: 8.248 ms
keith@keith=# select partman.create_parent('public.deliveries', 'id', 'partman', '15000000');
 create_parent 
---------------
 t
(1 row)

Time: 119.147 ms
keith@keith=# \d+ deliveries
                     Table "public.deliveries"
 Column |  Type  | Modifiers | Storage | Stats target | Description 
--------+--------+-----------+---------+--------------+-------------
 id     | bigint | not null  | plain   |              | 
Triggers:
    deliveries_part_trig BEFORE INSERT ON deliveries FOR EACH ROW EXECUTE PROCEDURE deliveries_part_trig_func()
Child tables: deliveries_p0,
              deliveries_p15000000,
              deliveries_p30000000,
              deliveries_p45000000,
              deliveries_p60000000
```

I can try with the full schema of your table, but I'm not sure that will really affect anything since partman doesn't touch anything outside of that, especially where you're getting that error.


Can you show me the source of the show_partitions function by doing
```
\sf partman.show_partitions
```
Only other thing I can think of at this point is an invalid version of a function got installed somehow. Just to clarify, you installed pg_partman 3.1.2 from scratch on this system?

**Comment by aysabzevar** [comment]
@keithf4 

1. I attached two files. ```hm-partman-show_partitions.txt``` is that one which does not work, but ```m1-partman-show_partitions.txt``` is another database that uses the older version of partman, but it works!
[hm-partman-show_partitions.txt](https://github.com/keithf4/pg_partman/files/1801516/hm-partman-show_partitions.txt)
[m1-partman-show_partitions.txt](https://github.com/keithf4/pg_partman/files/1801517/m1-partman-show_partitions.txt)

The weird thing is that, I'd installed partman on this database successfully before.

2. I installed partman and postgresql both from postgresql's official repository.
```
root@db-hm:~# cat /etc/apt/sources.list.d/pgdg.list 
deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
```

3. This server previously had partman that was working. After update, it didn't work anymore. Execution of ```CREATE EXTENSION pg_partman SCHEMA partman;``` failed, because it had already older version of partman. So, I removed partman schema and all functions and triggers related to partman. I tried to re-install it but I got that error that mentioned in the first comment.

4. By the way, although, it's not installed on the server successfully and does not work because of that error in the first comment, but ```pg_partman_bgw.interval``` executes hourly and log these into ```/var/log/postgresql/postgresql-9.6-main.log```

```
2018-03-12 06:26:51.026 +0330 [14581] LOG:  pg_partman dynamic background worker (dbname=hm) dynamic background worker initialized with role hm on database hm
2018-03-12 06:26:51.027 +0330 [14581] ERROR:  permission denied for schema partman at character 8
2018-03-12 06:26:51.027 +0330 [14581] QUERY:  SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)
2018-03-12 06:26:51.029 +0330 [4245] LOG:  worker process: pg_partman dynamic background worker (dbname=hm) (PID 14581) exited with exit code 1

2018-03-12 07:26:51.135 +0330 [19855] LOG:  pg_partman dynamic background worker (dbname=hm) dynamic background worker initialized with role hm on database hm
2018-03-12 07:26:51.136 +0330 [19855] ERROR:  permission denied for schema partman at character 8
2018-03-12 07:26:51.136 +0330 [19855] QUERY:  SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)
2018-03-12 07:26:51.138 +0330 [4245] LOG:  worker process: pg_partman dynamic background worker (dbname=hm) (PID 19855) exited with exit code 1


2018-03-12 08:26:51.271 +0330 [25122] LOG:  pg_partman dynamic background worker (dbname=hm) dynamic background worker initialized with role hm on database hm
2018-03-12 08:26:51.279 +0330 [25122] ERROR:  permission denied for schema partman at character 8
2018-03-12 08:26:51.279 +0330 [25122] QUERY:  SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)
2018-03-12 08:26:51.280 +0330 [4245] LOG:  worker process: pg_partman dynamic background worker (dbname=hm) (PID 25122) exited with exit code 1
```

Please let me know if you need anything else.

**Comment by keithf4** [comment]
The copy of show_partitions that you provided matches the version in 3.1.2, so I'm really not sure what's going on here. Not sure how you tried to remove partman before, but you should be able to uninstall it just using the `DROP EXTENSION` command to ensure everything is removed, not manually remove anything. It sounds like there may be some old/new functions somehow conflicting, but it's hard to say. Even trying to give me a dump of the schema won't really work because extension objects are not part of a dump, only the CREATE EXTENSION command is.

My only recommendation is to drop the extension as well as the schema you had pg_partman in and try installing it again. Be aware that that will remove any partition configurations you currently have in place, so you may want to copy the config table contents to another location first if you need to keep that.

The errors in your log are because you still have the background worker installed, but you didn't give whichever role you have defined to run pg_partman permissions to the `partman` schema.

**Comment by aysabzevar** [comment]
```DROP EXTENSION partman``` didn't drop partman, so I had to drop it manually again.
Unfortunately, drop extension partman didn't solve the problem and I got same error.

**Comment by keithf4** [comment]
It's `DROP EXTENSION pg_partman;`

If that didn't work, there is something very wrong with your installation.

**Comment by aysabzevar** [comment]
Sorry, It was a typo.
```
postgres@db-hm:~$ psql
psql (9.6.8)
Type "help" for help.

postgres=# \c hm
You are now connected to database "hm" as user "postgres".
hm=# \dx
                               List of installed extensions
    Name    | Version |   Schema   |                     Description                      
------------+---------+------------+------------------------------------------------------
 pg_partman | 3.1.2   | partman    | Extension to manage partitioned tables by time or ID
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

hm=# DROP EXTENSION pg_partman;
DROP EXTENSION
hm=# CREATE SCHEMA partman;
CREATE SCHEMA
hm=# CREATE EXTENSION pg_partman SCHEMA partman;
CREATE EXTENSION
hm=# SELECT partman.create_parent('public.deliveries', 'id', 'partman', '15000000');
ERROR:  invalid input syntax for integer: ""
CONTEXT: PL/pgSQL function show_partitions(text,text) line 81 at RETURN QUERY
SQL statement "SELECT partition_tablename                       FROM partman.show_partitions(p_parent_table, 'DESC') LIMIT 1"
PL/pgSQL function create_function_id(text,bigint) line 102 at SQL statement
SQL statement "SELECT partman.create_function_id(p_parent_table, v_job_id)"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 626 at PERFORM
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_function_id(text,bigint) line 298 at RAISE
SQL statement "SELECT partman.create_function_id(p_parent_table, v_job_id)"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 626 at PERFORM
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 670 at RAISE
hm=# 
```
Probably there is something wrong with type of column(s). I have to scrutiny to find out what is wrong with it.
Thanks for your time.

**Comment by aysabzevar** [comment]
I changed ```15000000``` to ```monthly``` and it didn't work!
@keithf4 Do you think this is related to our DB configurations or pg_partman extension installation too?
```
hm=# SELECT partman.create_parent('public.deliveries', 'id', 'partman', 'monthly');
ERROR:  invalid input syntax for integer: "monthly"
CONTEXT: PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 474 at assignment
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 670 at RAISE

```

**Comment by keithf4** [comment]
Your first comment changing the interval to `monthly` isn't going to work because the column and interval value are integer based and monthly is only for time-based partitioning. That would error out anyway, but because of your current issue, it's giving a misleading error.

There is definitely something wrong here. The parameter `p_use_run_maintenance` didn't just change datatypes, it also changed its name to `p_automatic_maintenance`. This was done in version 3.0.0. See the CHANGELOG for more details. Just changing the data type of the column likely isn't going to fix it because the change in data type isn't all that changed within the code.

What is your `search_path` set to? It sounds like you have multiple copies of pg_partman installed in different schemas and an old version is somehow getting called, despite you explicitly using the `partman` schema when you call `create_parent`.  I have unit tests that should make sure `search_path` settings being wrong don't cause an issue, so I'm really confused what's happening here if that's the issue.

This query should tell you if you have multiple versions of create_parent installed, which schema they're in and the argument signature
```
select p.proname, n.nspname, a.rolname, p.proargnames 
from pg_catalog.pg_proc p
join pg_catalog.pg_namespace n on p.pronamespace = n.oid
join pg_catalog.pg_authid a on p.proowner = a.oid
where p.proname = 'create_parent';
```

**Comment by ali-sattari** [comment]
The initial error in OP seems to be related to one or some invalid rows. 

Here is what I did:
- created a new table just like the original parent
- added inheritance of previous parent (and cascade of it's children) to this table
- ran create_parent function and got the same error. (`ERROR:  invalid input syntax for integer: ""`)
- removed inheritance of previous parent from this table, confirming the new table doesn't have any children
- ran create_parent and it worked without error
- re-inherited old tables to this new one and received no errors (naturally)

So while error is ambiguous, the cause is in data not the schema or partman.

I have encountered another issue with partitioning, which I will discuss in a new separate issue.

**Comment by keithf4** [comment]
Thanks for investigating further! I'm not sure how the data itself would be the issue. So you're saying you were running create_parent() on a table that already had existing child tables? It may be an issue in the name of the existing child tables. create_parent() can only be run against an existing partition set of the child tables already match pg_partman's naming conventions. If you have triggers in place, those will also have to be removed. See the `migration.md` document.

https://github.com/keithf4/pg_partman/blob/master/doc/migration.md

If that's not the issue, I would need the exact commands run and an example table with the exact schema and invalid data to reproduce this to try and debug what the issue is.

**Comment by keithf4** [comment]
So I just went back and looked at your original schema example. I'd completely missed you already had a child table there.
```
deliveries_OLD
```
That table is most likely the cause. It doesn't match the integer naming convention required by pg_partman and it's trying to parse `OLD` as an integer and giving you the original error produced. pg_partman cannot handle children that don't match the naming convention. I've tried and it's just way too complicated.

I'd recommend renaming that table with a suffix of whatever the lowest value contained in it is. If there are any values that will conflict with another existing child table, then you're going to have to get those values moved out to the appropriate child table. Again, see the migration document.

If you're just trying to partition an existing data-set that is not already partitioned, run create_parent() on the table with the data so the children are created there. You're not on PostgreSQL 10 yet and doing native partitioning, so the data can live in the parent and be partitioned out later.

**Comment by ali-sattari** [comment]
Good catch! It is in fact caused by `deliveries_OLD`, it is so obvious now! :man_facepalming: 

Due to another issue described in #210 I went ahead and partitioned it `monthly`, bypassing this issue along with it.

As a workaround, de-inheriting conflicting (or perhaps all) child tables from new parent and manually adjusting for `p_start_partition` in `create_parent` call would be easier, given one does not want to alter or manage old partitions (retention policy).

Thanks for your help Keith :+1:

**Comment by aysabzevar** [comment]
@keithf4 
Thanks for your help. It was a great help.
