### ISSUE TITLE
Error on insert in big, ID-partitioned table (check_name_length)

### ISSUE THREAD

**Issue by ali-sattari** [keithf4/pg_partman#210]
We are using partman on a table with roughly 2.5 billion rows. It was partitioned BY ID from the beginning and have been migrated through 2 major Postgres versions.
We have had some issues after last server migration and had to resort to manual partitioning of data for a while. Today I tried to dig into it and fix the issue.

What I tried:
- dropped extension
- created extension again
- created a new empty parent table
- ran create_parent on it (`SELECT partman.create_parent('public.deliverys', 'id', 'partman', '20000000', Null, 2, 'on', '2500000000')`)
- re inherited old parent and partitions (irrelevant)
- tried to insert into new partitioned parent table and got this error:

```
2018-03-17 13:03:04.179 +0330 [4108] myuser@mydb ERROR:  permission denied for schema partman at character 8
2018-03-17 13:03:04.179 +0330 [4108] myuser@mydb QUERY:  SELECT partman.check_name_length('deliverys', v_current_partition_id::text, TRUE)
2018-03-17 13:03:04.179 +0330 [4108] myuser@mydb CONTEXT:  PL/pgSQL function deliverys_part_trig_func() line 25 at assignment
2018-03-17 13:03:04.179 +0330 [4108] myuser@mydb STATEMENT:  insert into "deliverys".....
```
The last ID at the time was `2488403795` and the corresponding partition should have been `deliverys_p2500000000`

Having encountered this before, I tried this:
- ran `undo_partition_id` on new (empty) parent
- removed inheritance of old tables
- ran `create_parent` for a monthly partitioning (`SELECT partman.create_parent('public.deliverys', 'datetime', 'partman', 'monthly')`)
- tried to insert some rows and it worked.

My take is although Postgres default limit on identifier name is 63 bytes, but partman encounters  some internal issues in handling 22 character table names (`deliverys_p2500000000`). I am not sure if this is the case and how to verify it.

**Comment by keithf4** [comment]
Your error is a permissions issue. Ensure that any user you are running partman functions as has USAGE permissions to the `partman` schema. This includes roles that will be inserting to the given table since the check_name_length() function exists in the partition trigger (your logs are showing this is the "myuser" role).

However, that code branch only happens when data is inserted that is outside the current trigger optimization range of the existing trigger (after the explicit INSERT statements of the partition trigger; check the trigger function source). If that will be a frequent occurrence, I would recommend adjusting the `optimize_trigger` value to account for the "normal" range of data insertion. Data insertion outside that range works, but is MUCH slower.
https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md#tables

**Comment by ali-sattari** [comment]
Yup, the user didn't have any permission to partman schema, added `GRANT` for it.
So I gather it is working fine with time based partitioning because it was in predefined and optimized range. It shouldn't happen often, or at all, since this is an archive table and grows predictably in term of date-time and ID.

Thanks for your quick response.
