### ISSUE TITLE
type partman and native performance compare

### ISSUE THREAD

**Issue by jilongs** [keithf4/pg_partman#211]
You mentioned that "performance in both reads & writes is significantly better", do you have some rough number in mind?

**Comment by keithf4** [comment]
Currently reads do not have a significant difference in performance between trigger-based and native partitioning. That is something that will be coming in 11+.

For writes, the performance is pretty much like comparing a plain, single table to a partitioned one. The write performance of a natively partitioned table is only slightly slower than that. Depesz did some of this testing back before 10 was even released and found that to be the case

https://www.depesz.com/2017/02/06/waiting-for-postgresql-10-implement-table-partitioning/

If anything, it's probably gotten better since then.
