### ISSUE TITLE
run_maintenance removes inheritance for partitions created prior to adopting pg_partman

### ISSUE THREAD

**Issue by hopesea** [keithf4/pg_partman#48]
I have a number of existing tables which have been partitioned using an old scheme. I would like to transition to using pg_partman for this going forward.

On the first execution of the run_maintenance function, it doesn't recognise the format of my legacy partition names (in drop_partition_time function) which is understandable as our legacy naming scheme is different, and so calculates the v_partition_timestamp as "0001-01-01 00:00:00+00 BC". This lead to the removal of inheritance from all legacy partitions and the data in those partitions immediately becoming inaccessible to queries against the parent table. 

Would it not be preferable to ignore partitions that are not under pg_partman control and therefore don't yield valid timestamps when searching for partitions to drop during maintenance? Management of those partitions would be left to the user and the approach would make migrating from a legacy partition management scheme to pg_partman more feasible.

**Comment by keithf4** [comment]
I'm a bit confused as to how drop_partition_time() was even getting called. The condition below exists in run_maintenance() so that it will only do so if the retention option is turned on, which it is not by default
```
SELECT parent_table FROM @extschema@.part_config WHERE retention IS NOT NULL ...
```
So, that should not have happened unless you set an interval for `retention` in the `part_config` table.

Changing an existing partition set with a different pattern is a bit more involved. And turning on the retention policy is definitely something that cannot be done if all the children are not using the same naming pattern. At one time pg_partman did allow child partitions with a different naming pattern, but it actually made it harder to manage and add more features. If you're curious, it uses the following query to determine the latest child table:
```
SELECT show_partitions('parent_table', 'DESC') LIMIT 1
```
That function returns a list of all child tables in a set but in the expected, logical order. If you have child tables that don't match the pattern, this can throw that determination off.

I believe there likely is a way to migrate an existing partition set to pg_partman and I think it probably deserves its own documentation file. I'll see if I can work on that.

**Comment by hopesea** [comment]
Thanks for the response. You are correct - I did enable retention in the hopes that pg_partman would apply the retention policy to the partitions under its management and ignore legacy partitions.

An approach I could take is to disable pg_partman retention policy until all legacy partitions are no longer required in the active data set. Enabling retention thereafter should have no impact.
