### ISSUE TITLE
Running analyze for new partitions is mandatory?

### ISSUE THREAD

**Issue by dev1ant** [keithf4/pg_partman#59]
Hi.

Is running ANALYZE on parent table is mandatory after creating new partition? Although we don't have any records in parent table it takes some huge time to do it:
```
xivastore01e/xivadb M # select count(*) from only xiva.notifications;
 count
-------
     0
(1 row)

Time: 1.086 ms
xivastore01e/xivadb M # analyze xiva.notifications;
ANALYZE
Time: 157471.619 ms
xivastore01e/xivadb M #
```

Since `partman.run_maintenance` is a function and all its work is done in a single transaction we get locking problems when we call it. A [simple change](https://gist.github.com/dev1ant/9db61ad102a2bc2222fa) solves our problem but how secure is it?

We are using version 1.8.2 and `part_config` looks as following:
```
xivastore01e/xivadb M # select * from partman.part_config ;
-[ RECORD 1 ]--------+-------------------------------
parent_table         | xiva.notifications
type                 | time-static
part_interval        | 1 day
control              | event_dt
constraint_cols      | [null]
premake              | 15
inherit_fk           | t
retention            | 30 days
retention_schema     | [null]
retention_keep_table | t
retention_keep_index | t
datetime_string      | YYYY_MM_DD
last_partition       | xiva.notifications_p2015_05_29
use_run_maintenance  | t
jobmon               | t
undo_in_progress     | f

Time: 1.164 ms
xivastore01e/xivadb M #
```

**Comment by keithf4** [comment]
As of 1.8.0, there is a parameter to the `run_maintenance()` function to tell it to skip running the analyze if new partitions are created. If you look further down in the code, there is a section that checks both the variable you commented out and the `p_analyze` parameter passed into the creation function. `run_maintenance()` passes its `p_analyze` value into `create_partition_time()`. Both must be true for the analyze to actually happen. 

https://github.com/keithf4/pg_partman/blob/master/sql/functions/create_partition_time.sql#L258

However, as I state in the documentation for this feature, it is recommended that you schedule some other method of analyzing these tables if you do this. Otherwise constraint exclusion may not work properly. When you analyze the parent table of an inheritance set, it also analyzes all the children.

The other option is to call `run_maintenance()` individually for these tables that take a long time to analyze so it doesn't affect other partition sets. You can pass the parent table as a parameter like so: `run_maintenance('schema.table')`. Then to avoid general calls to `run_maintenance()` creating partitions for that table, in the `part_config` table, set `use_run_maintenance` to false for that partition set. When you call `run_maintenance()` directly on a partition set by passing its parent table, it ignores that config table option and runs it anyway.

Hope that helps.

**Comment by dev1ant** [comment]
Yep, thank you very much.
