### ISSUE TITLE
run_maintenance doesn't make new child partitions when too far behind

### ISSUE THREAD

**Issue by steven-sortable** [keithf4/pg_partman#67]
If the last partition for a table is older than the current partition should be (say, because `run_maintenance` wasn't called for a while), then `run_maintenance` disinherits/drops old child tables but doesn't create new child tables.  I think the cause is here:
https://github.com/keithf4/pg_partman/blob/master/sql/functions/run_maintenance.sql#L151
The condition `v_premade_count >= 0` was added in 2.1.0; in the scenario described, `v_premade_count` is negative, so no new child tables are produced.

(In my scenario there is no subpartitioning, so I think the rationale given in the comment preceding line 151 doesn't apply... but I don't quite see what that comment is getting at, so I'm not sure.)

**Comment by keithf4** [comment]
Hmm... thanks for catching that. Will look into it.

**Comment by lucasmo** [comment]
I am also being bitten by this bug. Thanks for reporting!

**Comment by keithf4** [comment]
This issue has been fixed in version 2.2.0. There's a bit of a change in behavior with time based partition behavior because of it, but I think it's for the better. Please see the CHANGELOG for more info.

Sorry for how long this took. As you can see, I had a lot to fix and account for in this release, most of which revolved around this change. :)
