### ISSUE TITLE
cant read data 

### ISSUE THREAD

**Issue by 208rishabh** [keithf4/pg_partman#70]
3 node cluster for postgres. Requirement: Data sharding+ replication + partitioning

Tech used: PostgreSQL-9.4, PG_Shard and PG_Partman

What I have done till now: I create master table on one node and worker on the other two. I shard my table on these nodes. I partition those shards on the workers.

What is working: I can insert properly from the master node. The data goes to the correct partition of the correct shard.

What is the issue: I cant read from the master node. Although, I can see the data on the shard and also on the partition by connecting to the worker node.

Any help, please?

**Comment by keithf4** [comment]
I've never used pg_shard myself, so I'm really not sure how the two would interact. If I have some time I can try to set things up and see, but I think you may be better off asking the pg_shard community. 

I'm not really doing anything different from the standard way partitioning is instructed here http://www.postgresql.org/docs/9.4/static/ddl-partitioning.html, so if it's not working with this extension, it's probably not working with normal partitioning or table inheritance in general.

**Comment by keithf4** [comment]
I've created an issue over on the pg_shard repo. Link is above (Issue #151). Haven't seen any responses there. I'd recommend trying to work with them to see what the issue may be at this time since I'm unsure of how pg_shard handles inheritance and they would be better able to answer that question. If you hear back from them and they point to an issue in pg_partman, please feel free to re-open this issue.
