### ISSUE TITLE
maintenance stops silently, if a new version is available

### ISSUE THREAD

**Issue by jw1u1** [keithf4/pg_partman#716]
we had 5.0.1 active, while the Binaries of 5.1 were already installed.
Neither the Background Worker nor manual run_maintenance calls created any premake partitions.
After updating the extension, premake worked as expected.
Please let run_maintenance at least complain about this Version Mismatch.

**Comment by keithf4** [comment]
The only files that would have mattered from the binaries is the shared library file. All the other plpgsql files on disk have no affect on what is happening in the database. They only get applied when you actually update the extension. 

There have been no changes to the shared library file since the 5.0 release, so the 5.1 library file being there would have made no difference

Can see there have been no changes for over a year now https://github.com/pgpartman/pg_partman/tree/development/src

If there were no errors being generated, then there should have been no issues with maintenance working. The only thing I can think that may have happened is you had no new data being inserted into the partition sets until after you happened to update pg_partman. By default, no new partitions are created in any partition set if no new data is being inserted.

**Comment by keithf4** [comment]
Going to close this issue for now. If it's still a problem please feel free to reopen it at any time and I can continue investigating further.
