### ISSUE TITLE
Feature request: SQL Only Extension export for RDS

### ISSUE THREAD

**Issue by andreijs** [keithf4/pg_partman#72]
What is this? Why is it here?
-----------------------------

So the pg_partman extension, which can be found here https://github.com/keithf4/pg_partman requires a little bit of manual manipulation in order to be suitable for installation of RDS, the general process is captured in this blog post http://www.databasesoup.com/2014/12/loading-pgpartman-on-rds-or-heroku.html

There were a few additional things required to make the current 1.8.5 version install correctly.

1. Clone pg_partman repository
2. Run `make`, which will produce the sql/pg_partman--1.8.5.sql files

Needs some modification to be able to run on RDS there is a gist for version 1.8.5.

It would be great if you could give me some pointers on how to make this work for any version? At the moment it was a manual task but I guess it could be done as a flag in the build process?

https://gist.github.com/andreijs/78e3d18ff19759e09b4b

**Comment by keithf4** [comment]
The major issue with this is supporting ongoing updates as that blog post states. The same manual edits being done to the sql file resulting from `make` also have to be done to all the update files. And then you have to be very careful to install all the updates in the proper order manually as well. One mistake and you've potentially completely broken the extension because there's no forced version dependency tree.

Unfortunately this is something that I cannot support doing at this time because there's way too many unpredictable variables. The folks at Amazon know this is a major shortcoming of RDS and have said they're working on ways to allow third-party extension installations. We'll just have to wait for that.

**Comment by andreijs** [comment]
Hey @keithf4, we are currently in the process of migrating from a data centre where we have the native extension installed into RDS. We have not really planned how we will do upgrades yet hence my question. 

I appreciate your quick response, fair enough I can ask a contact on some time lines, it would be great if native extensions would work on RDS.

It is hard to manage this at a large scale as you said.
