### ISSUE TITLE
run_maintenance still doesn't make new child partitions when too far behind

### ISSUE THREAD

**Issue by lucasmo** [keithf4/pg_partman#74]
This is in v2.2.1. There are two failure conditions.

#### No child partitions exist anymore due to expiry, but data exists in parent table
In this case, run_maintenance() does nothing. As a side effect, the trigger function is not updated, meaning that it can attempt to insert into tables that do not exist (this isn't a huge deal).

I believe this may be due to this code:
```sql
        IF v_max_time_parent > v_current_partition_timestamp THEN
            SELECT suffix_timestamp INTO v_current_partition_timestamp FROM @extschema@.show_partition_name(v_row.parent_table, v_max_time_parent::text);
        END IF;
        IF v_current_partition_timestamp IS NULL THEN
            -- Partition set is completely empty. Nothing to do
            CONTINUE;
        END IF;
```
At that point, `v_current_partition_timestamp` is null, so the `v_max_time_parent > v_current_partition_time` check fails.

#### Some child partitions exist, but they are very old and data in table is very old
This is coming back from a failure mode in which there is a large gap in the data. We want the new tables to exist to accommodate new data, but instead tables are only generated up to the last time point in the parent table or an existing child table plus premake.
 
As this is time based, we want to create time tables up to the current time plus premake (or we want to skip the data hole, and create time tables starting at the current time plus premake).

**Comment by lucasmo** [comment]
It looks like an old trigger was sitting around from pg_partman 1.x. We have a process that reaps old active partitions and aggregates the data inside them into archive partitions. This had removed all the child tables as no new child tables had existed.

For the second case, I am dealing with tables that are partitioned by hour. We typically keep 3 days of these hourly partitions around. The source of the data is very high volume and is very real time. Unfortunately, we have had periods due to maintenance where the source goes down for several days. It doesn't make sense to premake several days worth of tables in the future. It looks like this may be an issue with transitioning between pg_partman 2.0 and 2.1 versions - trying to use 2.1 does not work effectively to handle a database that was broken in a strange way by 2.0.

**Comment by keithf4** [comment]
Yeah for the 1.x to 2.x transition was trickier than I'd hoped it would be, which is part of the reason for the major version number change. The new trigger function would not be created unless maintenance ran successfully to create new child tables, which sounds like is what may have happened in your case. I wish I could've forced the re-creation of all trigger functions as part of the update, but the simple act of running the CREATE FUNCTION command as part of an extension install/update makes that function itself part of the extension, which would've broken things pretty badly.
I'd put notes concerning all this in the CHANGELOG and instructions for a way to manually force all trigger functions to be recreated. If you've still got anything running 1.x I'd recommend reviewing the 2.x release notes.

Not sure I see a problem pre-creating the additional tables, especially if you've got something that removes old ones to prevent a huge inheritance tree from forming. They sit empty and are ignored due to constraint exclusion. You having periods of maintenance far longer than your partitioning intervals is something I didn't account for and I'm not sure of an effective way to handle that in a general case. Not sure things are really "broken". I'd honestly used the premake config value for more than it really should have been used for and likely caused some bad habits in usage because of that. I'd recommend re-evaluating your usage of the extension with these new config options that are available. I am working on a way to try and backfill a gap in child tables if it occurs, so maybe that will help as well.

If you have any further issues or questions trying to find a way to use it, just let me know and I'll try to help.

**Comment by lucasmo** [comment]
I think what would be most useful in recovering from this situation would be a way to ask pg_partman to create the table useful for the "now" time period plus premake. Basically, a 'recover from downtime' function that would get pg_partman back up to speed. 

Obviously this doesn't make any sense in the 'id' partitioning scheme, as you're probably not missing any sequential data.

Thanks for advice!

**Comment by keithf4** [comment]
There's already a sort of 'recovery from downtime' built in, it's just not as explicit.
An extended downtime should cause the data to go to the parent and set off an alarm when it resumes. This shouldn't cause any performance issues if it's caught in time. And to recover from that, simply run the `partition_data_time` function (or the python script if it's a huge chunk of data that needs to be batched). That will move the data to the child tables and maintenance should proceed as normal from there.

Now, there is a gap in the child tables and I agree that could use some work. As I said I'm working on something to go back and fill that gap as part of a normal maintenance run. So, I think with that feature added in, your recovery method should be complete. In the mean time, data would go to the parent and you could again run the same method to fix it.

Unfortunately, not sure how long it'll be before I get the next minor release out with that feature. Been really busy lately.
