### ISSUE TITLE
run_maintenance() doesn't create new partitions if all partitions moved/deleted manualy

### ISSUE THREAD

**Issue by dturon** [keithf4/pg_partman#80]
Hi, i found some bug/unpredicted behavior when all partitions are deleted/moved somewere. This situation probably not happend in most use cases ... But I wrote some experimental postgresql extension for moving old partman tables to cstore_fdw(https://github.com/dturon/partman_to_cstore). I moved old tables and forgot setup cron job for maintenance function, when configured - all tables that was created with create_parent function was moved and no new child created with run_maintenance. Some example that produce same behavior

```sql
--pg (9.5beta1), partman 2.2.2
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman WITH SCHEMA partman ;

CREATE SCHEMA partman_test;
CREATE TABLE partman_test.test2_timestamptz(a timestamptz primary key, data int); 
INSERT INTO partman_test.test2_timestamptz VALUES (now(),0);

SELECT * FROM partman.create_parent(p_parent_table:='partman_test.test2_timestamptz', p_control:='a', p_type:='time', p_interval:='monthly', p_premake:=4, p_use_run_maintenance:=NULL::boolean, p_inherit_fk:=true, p_jobmon:=false, p_debug:=false);

/*
\dt partman_test.test*
                         Seznam relací
    Schéma    |           Jméno            |   Typ   | Vlastník 
--------------+----------------------------+---------+----------
 partman_test | test2_timestamptz          | tabulka | postgres
 partman_test | test2_timestamptz_p2015_09 | tabulka | postgres
 partman_test | test2_timestamptz_p2015_10 | tabulka | postgres
 partman_test | test2_timestamptz_p2015_11 | tabulka | postgres
 partman_test | test2_timestamptz_p2015_12 | tabulka | postgres
 partman_test | test2_timestamptz_p2016_01 | tabulka | postgres
 partman_test | test2_timestamptz_p2016_02 | tabulka | postgres
 partman_test | test2_timestamptz_p2016_03 | tabulka | postgres
 partman_test | test2_timestamptz_p2016_04 | tabulka | postgres
 partman_test | test2_timestamptz_p2016_05 | tabulka | postgres
*/

DROP TABLE partman_test.test2_timestamptz_p2015_09 ;
DROP TABLE partman_test.test2_timestamptz_p2015_10;
DROP TABLE partman_test.test2_timestamptz_p2015_11;
DROP TABLE partman_test.test2_timestamptz_p2015_12;
DROP TABLE partman_test.test2_timestamptz_p2016_01;
DROP TABLE partman_test.test2_timestamptz_p2016_02;
DROP TABLE partman_test.test2_timestamptz_p2016_03;
DROP TABLE partman_test.test2_timestamptz_p2016_04;
DROP TABLE partman_test.test2_timestamptz_p2016_05;

SELECT * FROM partman.run_maintenance(p_debug:=True);
NOTICE:  run_maint: parent_table: partman_test.test2_timestamptz, v_last_partition: <NULL>
NOTICE:  run_maint: v_current_partition_timestamp: <NULL>, v_max_time_parent: 2016-01-08 11:00:32.9257
 run_maintenance 
-----------------
 
/*
\dt partman_test.test2_timestamptz*
                     Seznam relací
    Schéma    |       Jméno       |   Typ   | Vlastník 
--------------+-------------------+---------+----------
 partman_test | test2_timestamptz | tabulka | postgres
*/
 ```
https://github.com/keithf4/pg_partman/blob/master/sql/functions/run_maintenance.sql#L285

v_premade_count IS NULL here ... so nothing happend

**Comment by keithf4** [comment]
There must be at least one child table in a partition set for pg_partman to work. Otherwise it has no idea what the current status of the data is so it cannot know what new partitions to make. For both time & ID, I've chosen to base new child table on the actual data contained in the partition set, not any sort of external method like `now()`.
If you put some data into the parent table, just run the `partition_data_time()` function to move it out and create a child table. `run_maintenance()` should work from then on.

**Comment by dturon** [comment]
Yes, i fix this situation exactly you wrote - with partition_data_time & run_maintenace :) Thanks

**Comment by keithf4** [comment]
No problem!

**Comment by scott-mead** [comment]
A question on this.... Am I going to have to always run partition_data_time?  ISTM that I should be able to exec run_maintenance() on a day and have it pre-create any missing partitions, n days out based on my policy.

**Comment by keithf4** [comment]
This situation presented in this issue was that all the child tables were removed. If there are no child tables at all, then pg_partman has no way to know what the next child table to create is. So the solution was to insert some data, run partition_data_time() to create a child table and then run_maintenance() worked.

If that is not your situation, please clarify the issue you're having.

I'm working on adding an option to pg_partman to continue creating child tables indefinitely for time-based partitioning, even if there's no new data. That should solve the issue of retention removing all child tables when no new data is inserted for long periods of time (although I would question a retention policy that short on a table with gaps of new data that large).

**Comment by scott-mead** [comment]
1. I created a parent table, ran create_parent() and validated that all partitions were created
1. I dropped the partition for tomorrow
1. I ran the run_maintenance() function, it did not re-create the missing partition.

**Comment by keithf4** [comment]
Do you have any data in the partition set? If not, it will not create any new partitions. That is what I'm working on fixing at the moment.

If it's not working when you have data, please create a new issue with an example to recreate the problem.

**Comment by keithf4** [comment]
Or... did you delete the partition for tomorrow and leave other partitions for future days there? If so, then it will never recreate that missing partition. I would question why you deleted that partition then if you need it there. I'm not sure how I'd easily account for partitions older than the newest one being deleted in an efficient manner. That would be better handled by monitoring for data going into the parent and then fixing it as needed.

**Comment by scott-mead** [comment]
I did both :)
1. I have been testing without data, but I'll run some tests with data next
1. I was just testing.  I also tried dropping just the newest (today + 4 ) partition and run_maintenance() did not re-create it.
