### ISSUE TITLE
reapply_constraints.py does not choose the same latest table as apply_constraints

### ISSUE THREAD

**Issue by lucasmo** [keithf4/pg_partman#89]
Specifically, apply_constraints looks for the most recent partition with any data in it and subtracts optimize_constraints + 1 intervals. reapply_constraints.py finds the most recent partition (including premake) and subtracts (2 * optimize_constraints) + 1 intervals.

**Comment by keithf4** [comment]
Woops! Missed that when I changed things to be based on actual data back in version 2.2.0. Will make the python script work like the plpgsql function.
Thanks!

**Comment by keithf4** [comment]
Actually, going to change `apply_constraints()` to base itself of the latest actual partition and not the data. Making the python function base it off data is trickier than I though. Since I'll have it be optional in the next version whether time-based partitions continue to be made even with no new data, it should work just as well. I think that's probably more intuitive as well.

**Comment by keithf4** [comment]
Version 2.3.0 has been released and this has been fixed. I reverted the behavior of maintenance placing the old constraints to the way it was before v2.2.0. It now bases it on the current partition and doesn't care about the data in the partition set. The python script has been updated to do this properly as well.

Let me know if things are working ok for you. Thanks for the bug report!
