### ISSUE TITLE
create_parent on existing big table

### ISSUE THREAD

**Issue by red-led** [keithf4/pg_partman#93]
Hi!
First of all, thanks for your work!

I started to testing this extension and have some (may be newbie :) questions:

1. I have table which is pretty big already and want to split it on partitions. As I see calling ```create_parent()``` will only create next ```p_premake``` tables for me, but would not move any data from parent table. Even if I'm passing ```p_start_partition = '0'``` all data still in original table and not moved to childs. Are there any "ready to use" way to do this? May be just some advises?

2. Pretty same as previous. For example, I have serial-based partition set with ```use_run_maintenance = false```. If current partition is full, new rows are inserted into parent table as I see. Will they move into new partition on next ```run_maintenance()``` call?

3. I have table like this: 
```sql
CREATE TABLE logs (
    id      serial,
    sent    timestamp with time zone,
    message text,
);
```
and I know exactly that data in it never changes, only inserts. So it's good idea to add constraint on timestamp field when partition is full and next is used. Will ```p_constraint_cols``` argument of ```create_parent()``` make this for me or I should make it manually?

**Comment by keithf4** [comment]
1) The `create_parent()` function only creates child tables. It never moves data, not matter what parameters you send. This is to allow it to work as quickly as possibly on tables currently in production use without blocking for long periods of time. As soon as `create_parent()` finishes running, any new writes should redirect the data to child tables. If you then need to partition data still left in the parent, I recommend looking at the `partition_data.py` python script. This allows you to partition data in predictable intervals with minimal blocking.

2) For serial partitioning and `use_run_maintenance` set to false, as soon as the "current" partition reaches 50% of its max value, it should create new child tables. If you have no data in the child tables, you'll need to partition the data out as I recommend in step 1. There may be a period of time when you're still partitioning data out where things may not work as expected (since the child table isn't at 50% mark because parent has that data). Rest assured that if the child table cannot be found by the partitioning trigger, it will just insert it to the parent so no data is lost. Once all the data has been moved out of the parent, things should work as expected.

3) I'm assuming your example here is partitioned by the ID column and you also want a constraint on the time column? If so, then yes, the additional constraint management by pg_partman can handle this for you. There is an `optimize_constraint` column in the `part_config` table you can adjust to tell it how soon you want it to apply those additional constraints. By default the value is 30, so it applies the additional constraints 30 partitions back.

**Comment by red-led** [comment]
Thanks! Now it's all clear for me!
